/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsRouteRouteImport } from './routes/clients/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ForgotPasswordRouteRouteImport } from './routes/forgot-password/route'
import { Route as FreelancersRouteRouteImport } from './routes/freelancers/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as ResetPasswordRouteRouteImport } from './routes/reset-password/route'
import { Route as SuccessRouteRouteImport } from './routes/success/route'
import { Route as ClientsUserIdRouteImport } from './routes/clients/$userId'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardFreelancerRouteRouteImport } from './routes/dashboard/freelancer/route'
import { Route as DashboardHirerRouteRouteImport } from './routes/dashboard/hirer/route'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as FreelancersIndexRouteImport } from './routes/freelancers/index'
import { Route as FreelancersUserIdRouteImport } from './routes/freelancers/$userId'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as SuccessIndexRouteImport } from './routes/success/index'
import { Route as DashboardFreelancerIndexRouteImport } from './routes/dashboard/freelancer/index'
import { Route as DashboardFreelancerMessagesRouteImport } from './routes/dashboard/freelancer/messages'
import { Route as DashboardFreelancerProfileRouteImport } from './routes/dashboard/freelancer/profile'
import { Route as DashboardFreelancerProposalsRouteImport } from './routes/dashboard/freelancer/proposals'
import { Route as DashboardHirerIndexRouteImport } from './routes/dashboard/hirer/index'
import { Route as DashboardHirerMessagesRouteImport } from './routes/dashboard/hirer/messages'
import { Route as DashboardHirerProfileRouteImport } from './routes/dashboard/hirer/profile'
import { Route as DashboardAdminVerificationsIndexRouteImport } from './routes/dashboard/admin/verifications/index'
import { Route as DashboardFreelancerContractsIndexRouteImport } from './routes/dashboard/freelancer/contracts/index'
import { Route as DashboardFreelancerContractsContractIdRouteImport } from './routes/dashboard/freelancer/contracts/$contractId'
import { Route as DashboardFreelancerJobsSlugRouteImport } from './routes/dashboard/freelancer/jobs/$slug'
import { Route as DashboardFreelancerPaymentsIndexRouteImport } from './routes/dashboard/freelancer/payments/index'
import { Route as DashboardHirerContractsIndexRouteImport } from './routes/dashboard/hirer/contracts/index'
import { Route as DashboardHirerContractsContractIdRouteImport } from './routes/dashboard/hirer/contracts/$contractId'
import { Route as DashboardHirerJobsJobIdRouteImport } from './routes/dashboard/hirer/jobs/$jobId'
import { Route as DashboardHirerJobsNewRouteImport } from './routes/dashboard/hirer/jobs/new'
import { Route as DashboardHirerPaymentsIndexRouteImport } from './routes/dashboard/hirer/payments/index'
import { Route as DashboardOnboardingRoleIndexRouteImport } from './routes/dashboard/onboarding/role/index'
import { Route as DashboardHirerJobsJobIdProposalsRouteImport } from './routes/dashboard/hirer/jobs/$jobId.proposals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRouteRoute = ClientsRouteRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRouteRoute = ForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancersRouteRoute = FreelancersRouteRouteImport.update({
  id: '/freelancers',
  path: '/freelancers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRouteRoute = ResetPasswordRouteRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRouteRoute = SuccessRouteRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsUserIdRoute = ClientsUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ClientsRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFreelancerRouteRoute =
  DashboardFreelancerRouteRouteImport.update({
    id: '/freelancer',
    path: '/freelancer',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardHirerRouteRoute = DashboardHirerRouteRouteImport.update({
  id: '/hirer',
  path: '/hirer',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForgotPasswordRouteRoute,
} as any)
const FreelancersIndexRoute = FreelancersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FreelancersRouteRoute,
} as any)
const FreelancersUserIdRoute = FreelancersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => FreelancersRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResetPasswordRouteRoute,
} as any)
const SuccessIndexRoute = SuccessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuccessRouteRoute,
} as any)
const DashboardFreelancerIndexRoute =
  DashboardFreelancerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardFreelancerRouteRoute,
  } as any)
const DashboardFreelancerMessagesRoute =
  DashboardFreelancerMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => DashboardFreelancerRouteRoute,
  } as any)
const DashboardFreelancerProfileRoute =
  DashboardFreelancerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardFreelancerRouteRoute,
  } as any)
const DashboardFreelancerProposalsRoute =
  DashboardFreelancerProposalsRouteImport.update({
    id: '/proposals',
    path: '/proposals',
    getParentRoute: () => DashboardFreelancerRouteRoute,
  } as any)
const DashboardHirerIndexRoute = DashboardHirerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardHirerRouteRoute,
} as any)
const DashboardHirerMessagesRoute = DashboardHirerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardHirerRouteRoute,
} as any)
const DashboardHirerProfileRoute = DashboardHirerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardHirerRouteRoute,
} as any)
const DashboardAdminVerificationsIndexRoute =
  DashboardAdminVerificationsIndexRouteImport.update({
    id: '/admin/verifications/',
    path: '/admin/verifications/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardFreelancerContractsIndexRoute =
  DashboardFreelancerContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => DashboardFreelancerRouteRoute,
  } as any)
const DashboardFreelancerContractsContractIdRoute =
  DashboardFreelancerContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => DashboardFreelancerRouteRoute,
  } as any)
const DashboardFreelancerJobsSlugRoute =
  DashboardFreelancerJobsSlugRouteImport.update({
    id: '/jobs/$slug',
    path: '/jobs/$slug',
    getParentRoute: () => DashboardFreelancerRouteRoute,
  } as any)
const DashboardFreelancerPaymentsIndexRoute =
  DashboardFreelancerPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => DashboardFreelancerRouteRoute,
  } as any)
const DashboardHirerContractsIndexRoute =
  DashboardHirerContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => DashboardHirerRouteRoute,
  } as any)
const DashboardHirerContractsContractIdRoute =
  DashboardHirerContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => DashboardHirerRouteRoute,
  } as any)
const DashboardHirerJobsJobIdRoute = DashboardHirerJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => DashboardHirerRouteRoute,
} as any)
const DashboardHirerJobsNewRoute = DashboardHirerJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => DashboardHirerRouteRoute,
} as any)
const DashboardHirerPaymentsIndexRoute =
  DashboardHirerPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => DashboardHirerRouteRoute,
  } as any)
const DashboardOnboardingRoleIndexRoute =
  DashboardOnboardingRoleIndexRouteImport.update({
    id: '/onboarding/role/',
    path: '/onboarding/role/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardHirerJobsJobIdProposalsRoute =
  DashboardHirerJobsJobIdProposalsRouteImport.update({
    id: '/proposals',
    path: '/proposals',
    getParentRoute: () => DashboardHirerJobsJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRouteRouteWithChildren
  '/freelancers': typeof FreelancersRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRouteRouteWithChildren
  '/success': typeof SuccessRouteRouteWithChildren
  '/dashboard/freelancer': typeof DashboardFreelancerRouteRouteWithChildren
  '/dashboard/hirer': typeof DashboardHirerRouteRouteWithChildren
  '/clients/$userId': typeof ClientsUserIdRoute
  '/freelancers/$userId': typeof FreelancersUserIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/freelancers/': typeof FreelancersIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/success/': typeof SuccessIndexRoute
  '/dashboard/freelancer/messages': typeof DashboardFreelancerMessagesRoute
  '/dashboard/freelancer/profile': typeof DashboardFreelancerProfileRoute
  '/dashboard/freelancer/proposals': typeof DashboardFreelancerProposalsRoute
  '/dashboard/hirer/messages': typeof DashboardHirerMessagesRoute
  '/dashboard/hirer/profile': typeof DashboardHirerProfileRoute
  '/dashboard/freelancer/': typeof DashboardFreelancerIndexRoute
  '/dashboard/hirer/': typeof DashboardHirerIndexRoute
  '/dashboard/freelancer/contracts/$contractId': typeof DashboardFreelancerContractsContractIdRoute
  '/dashboard/freelancer/jobs/$slug': typeof DashboardFreelancerJobsSlugRoute
  '/dashboard/hirer/contracts/$contractId': typeof DashboardHirerContractsContractIdRoute
  '/dashboard/hirer/jobs/$jobId': typeof DashboardHirerJobsJobIdRouteWithChildren
  '/dashboard/hirer/jobs/new': typeof DashboardHirerJobsNewRoute
  '/dashboard/admin/verifications/': typeof DashboardAdminVerificationsIndexRoute
  '/dashboard/freelancer/contracts/': typeof DashboardFreelancerContractsIndexRoute
  '/dashboard/freelancer/payments/': typeof DashboardFreelancerPaymentsIndexRoute
  '/dashboard/hirer/contracts/': typeof DashboardHirerContractsIndexRoute
  '/dashboard/hirer/payments/': typeof DashboardHirerPaymentsIndexRoute
  '/dashboard/onboarding/role/': typeof DashboardOnboardingRoleIndexRoute
  '/dashboard/hirer/jobs/$jobId/proposals': typeof DashboardHirerJobsJobIdProposalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteRouteWithChildren
  '/clients/$userId': typeof ClientsUserIdRoute
  '/freelancers/$userId': typeof FreelancersUserIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/freelancers': typeof FreelancersIndexRoute
  '/login': typeof LoginIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/success': typeof SuccessIndexRoute
  '/dashboard/freelancer/messages': typeof DashboardFreelancerMessagesRoute
  '/dashboard/freelancer/profile': typeof DashboardFreelancerProfileRoute
  '/dashboard/freelancer/proposals': typeof DashboardFreelancerProposalsRoute
  '/dashboard/hirer/messages': typeof DashboardHirerMessagesRoute
  '/dashboard/hirer/profile': typeof DashboardHirerProfileRoute
  '/dashboard/freelancer': typeof DashboardFreelancerIndexRoute
  '/dashboard/hirer': typeof DashboardHirerIndexRoute
  '/dashboard/freelancer/contracts/$contractId': typeof DashboardFreelancerContractsContractIdRoute
  '/dashboard/freelancer/jobs/$slug': typeof DashboardFreelancerJobsSlugRoute
  '/dashboard/hirer/contracts/$contractId': typeof DashboardHirerContractsContractIdRoute
  '/dashboard/hirer/jobs/$jobId': typeof DashboardHirerJobsJobIdRouteWithChildren
  '/dashboard/hirer/jobs/new': typeof DashboardHirerJobsNewRoute
  '/dashboard/admin/verifications': typeof DashboardAdminVerificationsIndexRoute
  '/dashboard/freelancer/contracts': typeof DashboardFreelancerContractsIndexRoute
  '/dashboard/freelancer/payments': typeof DashboardFreelancerPaymentsIndexRoute
  '/dashboard/hirer/contracts': typeof DashboardHirerContractsIndexRoute
  '/dashboard/hirer/payments': typeof DashboardHirerPaymentsIndexRoute
  '/dashboard/onboarding/role': typeof DashboardOnboardingRoleIndexRoute
  '/dashboard/hirer/jobs/$jobId/proposals': typeof DashboardHirerJobsJobIdProposalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRouteRouteWithChildren
  '/freelancers': typeof FreelancersRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRouteRouteWithChildren
  '/success': typeof SuccessRouteRouteWithChildren
  '/dashboard/freelancer': typeof DashboardFreelancerRouteRouteWithChildren
  '/dashboard/hirer': typeof DashboardHirerRouteRouteWithChildren
  '/clients/$userId': typeof ClientsUserIdRoute
  '/freelancers/$userId': typeof FreelancersUserIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/freelancers/': typeof FreelancersIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/success/': typeof SuccessIndexRoute
  '/dashboard/freelancer/messages': typeof DashboardFreelancerMessagesRoute
  '/dashboard/freelancer/profile': typeof DashboardFreelancerProfileRoute
  '/dashboard/freelancer/proposals': typeof DashboardFreelancerProposalsRoute
  '/dashboard/hirer/messages': typeof DashboardHirerMessagesRoute
  '/dashboard/hirer/profile': typeof DashboardHirerProfileRoute
  '/dashboard/freelancer/': typeof DashboardFreelancerIndexRoute
  '/dashboard/hirer/': typeof DashboardHirerIndexRoute
  '/dashboard/freelancer/contracts/$contractId': typeof DashboardFreelancerContractsContractIdRoute
  '/dashboard/freelancer/jobs/$slug': typeof DashboardFreelancerJobsSlugRoute
  '/dashboard/hirer/contracts/$contractId': typeof DashboardHirerContractsContractIdRoute
  '/dashboard/hirer/jobs/$jobId': typeof DashboardHirerJobsJobIdRouteWithChildren
  '/dashboard/hirer/jobs/new': typeof DashboardHirerJobsNewRoute
  '/dashboard/admin/verifications/': typeof DashboardAdminVerificationsIndexRoute
  '/dashboard/freelancer/contracts/': typeof DashboardFreelancerContractsIndexRoute
  '/dashboard/freelancer/payments/': typeof DashboardFreelancerPaymentsIndexRoute
  '/dashboard/hirer/contracts/': typeof DashboardHirerContractsIndexRoute
  '/dashboard/hirer/payments/': typeof DashboardHirerPaymentsIndexRoute
  '/dashboard/onboarding/role/': typeof DashboardOnboardingRoleIndexRoute
  '/dashboard/hirer/jobs/$jobId/proposals': typeof DashboardHirerJobsJobIdProposalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/forgot-password'
    | '/freelancers'
    | '/login'
    | '/reset-password'
    | '/success'
    | '/dashboard/freelancer'
    | '/dashboard/hirer'
    | '/clients/$userId'
    | '/freelancers/$userId'
    | '/dashboard/'
    | '/forgot-password/'
    | '/freelancers/'
    | '/login/'
    | '/reset-password/'
    | '/success/'
    | '/dashboard/freelancer/messages'
    | '/dashboard/freelancer/profile'
    | '/dashboard/freelancer/proposals'
    | '/dashboard/hirer/messages'
    | '/dashboard/hirer/profile'
    | '/dashboard/freelancer/'
    | '/dashboard/hirer/'
    | '/dashboard/freelancer/contracts/$contractId'
    | '/dashboard/freelancer/jobs/$slug'
    | '/dashboard/hirer/contracts/$contractId'
    | '/dashboard/hirer/jobs/$jobId'
    | '/dashboard/hirer/jobs/new'
    | '/dashboard/admin/verifications/'
    | '/dashboard/freelancer/contracts/'
    | '/dashboard/freelancer/payments/'
    | '/dashboard/hirer/contracts/'
    | '/dashboard/hirer/payments/'
    | '/dashboard/onboarding/role/'
    | '/dashboard/hirer/jobs/$jobId/proposals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/clients/$userId'
    | '/freelancers/$userId'
    | '/dashboard'
    | '/forgot-password'
    | '/freelancers'
    | '/login'
    | '/reset-password'
    | '/success'
    | '/dashboard/freelancer/messages'
    | '/dashboard/freelancer/profile'
    | '/dashboard/freelancer/proposals'
    | '/dashboard/hirer/messages'
    | '/dashboard/hirer/profile'
    | '/dashboard/freelancer'
    | '/dashboard/hirer'
    | '/dashboard/freelancer/contracts/$contractId'
    | '/dashboard/freelancer/jobs/$slug'
    | '/dashboard/hirer/contracts/$contractId'
    | '/dashboard/hirer/jobs/$jobId'
    | '/dashboard/hirer/jobs/new'
    | '/dashboard/admin/verifications'
    | '/dashboard/freelancer/contracts'
    | '/dashboard/freelancer/payments'
    | '/dashboard/hirer/contracts'
    | '/dashboard/hirer/payments'
    | '/dashboard/onboarding/role'
    | '/dashboard/hirer/jobs/$jobId/proposals'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/dashboard'
    | '/forgot-password'
    | '/freelancers'
    | '/login'
    | '/reset-password'
    | '/success'
    | '/dashboard/freelancer'
    | '/dashboard/hirer'
    | '/clients/$userId'
    | '/freelancers/$userId'
    | '/dashboard/'
    | '/forgot-password/'
    | '/freelancers/'
    | '/login/'
    | '/reset-password/'
    | '/success/'
    | '/dashboard/freelancer/messages'
    | '/dashboard/freelancer/profile'
    | '/dashboard/freelancer/proposals'
    | '/dashboard/hirer/messages'
    | '/dashboard/hirer/profile'
    | '/dashboard/freelancer/'
    | '/dashboard/hirer/'
    | '/dashboard/freelancer/contracts/$contractId'
    | '/dashboard/freelancer/jobs/$slug'
    | '/dashboard/hirer/contracts/$contractId'
    | '/dashboard/hirer/jobs/$jobId'
    | '/dashboard/hirer/jobs/new'
    | '/dashboard/admin/verifications/'
    | '/dashboard/freelancer/contracts/'
    | '/dashboard/freelancer/payments/'
    | '/dashboard/hirer/contracts/'
    | '/dashboard/hirer/payments/'
    | '/dashboard/onboarding/role/'
    | '/dashboard/hirer/jobs/$jobId/proposals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRouteRoute: typeof ClientsRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ForgotPasswordRouteRoute: typeof ForgotPasswordRouteRouteWithChildren
  FreelancersRouteRoute: typeof FreelancersRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  ResetPasswordRouteRoute: typeof ResetPasswordRouteRouteWithChildren
  SuccessRouteRoute: typeof SuccessRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancers': {
      id: '/freelancers'
      path: '/freelancers'
      fullPath: '/freelancers'
      preLoaderRoute: typeof FreelancersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$userId': {
      id: '/clients/$userId'
      path: '/$userId'
      fullPath: '/clients/$userId'
      preLoaderRoute: typeof ClientsUserIdRouteImport
      parentRoute: typeof ClientsRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/freelancer': {
      id: '/dashboard/freelancer'
      path: '/freelancer'
      fullPath: '/dashboard/freelancer'
      preLoaderRoute: typeof DashboardFreelancerRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/hirer': {
      id: '/dashboard/hirer'
      path: '/hirer'
      fullPath: '/dashboard/hirer'
      preLoaderRoute: typeof DashboardHirerRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof ForgotPasswordRouteRoute
    }
    '/freelancers/': {
      id: '/freelancers/'
      path: '/'
      fullPath: '/freelancers/'
      preLoaderRoute: typeof FreelancersIndexRouteImport
      parentRoute: typeof FreelancersRouteRoute
    }
    '/freelancers/$userId': {
      id: '/freelancers/$userId'
      path: '/$userId'
      fullPath: '/freelancers/$userId'
      preLoaderRoute: typeof FreelancersUserIdRouteImport
      parentRoute: typeof FreelancersRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof ResetPasswordRouteRoute
    }
    '/success/': {
      id: '/success/'
      path: '/'
      fullPath: '/success/'
      preLoaderRoute: typeof SuccessIndexRouteImport
      parentRoute: typeof SuccessRouteRoute
    }
    '/dashboard/freelancer/': {
      id: '/dashboard/freelancer/'
      path: '/'
      fullPath: '/dashboard/freelancer/'
      preLoaderRoute: typeof DashboardFreelancerIndexRouteImport
      parentRoute: typeof DashboardFreelancerRouteRoute
    }
    '/dashboard/freelancer/messages': {
      id: '/dashboard/freelancer/messages'
      path: '/messages'
      fullPath: '/dashboard/freelancer/messages'
      preLoaderRoute: typeof DashboardFreelancerMessagesRouteImport
      parentRoute: typeof DashboardFreelancerRouteRoute
    }
    '/dashboard/freelancer/profile': {
      id: '/dashboard/freelancer/profile'
      path: '/profile'
      fullPath: '/dashboard/freelancer/profile'
      preLoaderRoute: typeof DashboardFreelancerProfileRouteImport
      parentRoute: typeof DashboardFreelancerRouteRoute
    }
    '/dashboard/freelancer/proposals': {
      id: '/dashboard/freelancer/proposals'
      path: '/proposals'
      fullPath: '/dashboard/freelancer/proposals'
      preLoaderRoute: typeof DashboardFreelancerProposalsRouteImport
      parentRoute: typeof DashboardFreelancerRouteRoute
    }
    '/dashboard/hirer/': {
      id: '/dashboard/hirer/'
      path: '/'
      fullPath: '/dashboard/hirer/'
      preLoaderRoute: typeof DashboardHirerIndexRouteImport
      parentRoute: typeof DashboardHirerRouteRoute
    }
    '/dashboard/hirer/messages': {
      id: '/dashboard/hirer/messages'
      path: '/messages'
      fullPath: '/dashboard/hirer/messages'
      preLoaderRoute: typeof DashboardHirerMessagesRouteImport
      parentRoute: typeof DashboardHirerRouteRoute
    }
    '/dashboard/hirer/profile': {
      id: '/dashboard/hirer/profile'
      path: '/profile'
      fullPath: '/dashboard/hirer/profile'
      preLoaderRoute: typeof DashboardHirerProfileRouteImport
      parentRoute: typeof DashboardHirerRouteRoute
    }
    '/dashboard/admin/verifications/': {
      id: '/dashboard/admin/verifications/'
      path: '/admin/verifications'
      fullPath: '/dashboard/admin/verifications/'
      preLoaderRoute: typeof DashboardAdminVerificationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/freelancer/contracts/': {
      id: '/dashboard/freelancer/contracts/'
      path: '/contracts'
      fullPath: '/dashboard/freelancer/contracts/'
      preLoaderRoute: typeof DashboardFreelancerContractsIndexRouteImport
      parentRoute: typeof DashboardFreelancerRouteRoute
    }
    '/dashboard/freelancer/contracts/$contractId': {
      id: '/dashboard/freelancer/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/dashboard/freelancer/contracts/$contractId'
      preLoaderRoute: typeof DashboardFreelancerContractsContractIdRouteImport
      parentRoute: typeof DashboardFreelancerRouteRoute
    }
    '/dashboard/freelancer/jobs/$slug': {
      id: '/dashboard/freelancer/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/dashboard/freelancer/jobs/$slug'
      preLoaderRoute: typeof DashboardFreelancerJobsSlugRouteImport
      parentRoute: typeof DashboardFreelancerRouteRoute
    }
    '/dashboard/freelancer/payments/': {
      id: '/dashboard/freelancer/payments/'
      path: '/payments'
      fullPath: '/dashboard/freelancer/payments/'
      preLoaderRoute: typeof DashboardFreelancerPaymentsIndexRouteImport
      parentRoute: typeof DashboardFreelancerRouteRoute
    }
    '/dashboard/hirer/contracts/': {
      id: '/dashboard/hirer/contracts/'
      path: '/contracts'
      fullPath: '/dashboard/hirer/contracts/'
      preLoaderRoute: typeof DashboardHirerContractsIndexRouteImport
      parentRoute: typeof DashboardHirerRouteRoute
    }
    '/dashboard/hirer/contracts/$contractId': {
      id: '/dashboard/hirer/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/dashboard/hirer/contracts/$contractId'
      preLoaderRoute: typeof DashboardHirerContractsContractIdRouteImport
      parentRoute: typeof DashboardHirerRouteRoute
    }
    '/dashboard/hirer/jobs/$jobId': {
      id: '/dashboard/hirer/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/dashboard/hirer/jobs/$jobId'
      preLoaderRoute: typeof DashboardHirerJobsJobIdRouteImport
      parentRoute: typeof DashboardHirerRouteRoute
    }
    '/dashboard/hirer/jobs/new': {
      id: '/dashboard/hirer/jobs/new'
      path: '/jobs/new'
      fullPath: '/dashboard/hirer/jobs/new'
      preLoaderRoute: typeof DashboardHirerJobsNewRouteImport
      parentRoute: typeof DashboardHirerRouteRoute
    }
    '/dashboard/hirer/payments/': {
      id: '/dashboard/hirer/payments/'
      path: '/payments'
      fullPath: '/dashboard/hirer/payments/'
      preLoaderRoute: typeof DashboardHirerPaymentsIndexRouteImport
      parentRoute: typeof DashboardHirerRouteRoute
    }
    '/dashboard/onboarding/role/': {
      id: '/dashboard/onboarding/role/'
      path: '/onboarding/role'
      fullPath: '/dashboard/onboarding/role/'
      preLoaderRoute: typeof DashboardOnboardingRoleIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/hirer/jobs/$jobId/proposals': {
      id: '/dashboard/hirer/jobs/$jobId/proposals'
      path: '/proposals'
      fullPath: '/dashboard/hirer/jobs/$jobId/proposals'
      preLoaderRoute: typeof DashboardHirerJobsJobIdProposalsRouteImport
      parentRoute: typeof DashboardHirerJobsJobIdRoute
    }
  }
}

interface ClientsRouteRouteChildren {
  ClientsUserIdRoute: typeof ClientsUserIdRoute
}

const ClientsRouteRouteChildren: ClientsRouteRouteChildren = {
  ClientsUserIdRoute: ClientsUserIdRoute,
}

const ClientsRouteRouteWithChildren = ClientsRouteRoute._addFileChildren(
  ClientsRouteRouteChildren,
)

interface DashboardFreelancerRouteRouteChildren {
  DashboardFreelancerMessagesRoute: typeof DashboardFreelancerMessagesRoute
  DashboardFreelancerProfileRoute: typeof DashboardFreelancerProfileRoute
  DashboardFreelancerProposalsRoute: typeof DashboardFreelancerProposalsRoute
  DashboardFreelancerIndexRoute: typeof DashboardFreelancerIndexRoute
  DashboardFreelancerContractsContractIdRoute: typeof DashboardFreelancerContractsContractIdRoute
  DashboardFreelancerJobsSlugRoute: typeof DashboardFreelancerJobsSlugRoute
  DashboardFreelancerContractsIndexRoute: typeof DashboardFreelancerContractsIndexRoute
  DashboardFreelancerPaymentsIndexRoute: typeof DashboardFreelancerPaymentsIndexRoute
}

const DashboardFreelancerRouteRouteChildren: DashboardFreelancerRouteRouteChildren =
  {
    DashboardFreelancerMessagesRoute: DashboardFreelancerMessagesRoute,
    DashboardFreelancerProfileRoute: DashboardFreelancerProfileRoute,
    DashboardFreelancerProposalsRoute: DashboardFreelancerProposalsRoute,
    DashboardFreelancerIndexRoute: DashboardFreelancerIndexRoute,
    DashboardFreelancerContractsContractIdRoute:
      DashboardFreelancerContractsContractIdRoute,
    DashboardFreelancerJobsSlugRoute: DashboardFreelancerJobsSlugRoute,
    DashboardFreelancerContractsIndexRoute:
      DashboardFreelancerContractsIndexRoute,
    DashboardFreelancerPaymentsIndexRoute:
      DashboardFreelancerPaymentsIndexRoute,
  }

const DashboardFreelancerRouteRouteWithChildren =
  DashboardFreelancerRouteRoute._addFileChildren(
    DashboardFreelancerRouteRouteChildren,
  )

interface DashboardHirerJobsJobIdRouteChildren {
  DashboardHirerJobsJobIdProposalsRoute: typeof DashboardHirerJobsJobIdProposalsRoute
}

const DashboardHirerJobsJobIdRouteChildren: DashboardHirerJobsJobIdRouteChildren =
  {
    DashboardHirerJobsJobIdProposalsRoute:
      DashboardHirerJobsJobIdProposalsRoute,
  }

const DashboardHirerJobsJobIdRouteWithChildren =
  DashboardHirerJobsJobIdRoute._addFileChildren(
    DashboardHirerJobsJobIdRouteChildren,
  )

interface DashboardHirerRouteRouteChildren {
  DashboardHirerMessagesRoute: typeof DashboardHirerMessagesRoute
  DashboardHirerProfileRoute: typeof DashboardHirerProfileRoute
  DashboardHirerIndexRoute: typeof DashboardHirerIndexRoute
  DashboardHirerContractsContractIdRoute: typeof DashboardHirerContractsContractIdRoute
  DashboardHirerJobsJobIdRoute: typeof DashboardHirerJobsJobIdRouteWithChildren
  DashboardHirerJobsNewRoute: typeof DashboardHirerJobsNewRoute
  DashboardHirerContractsIndexRoute: typeof DashboardHirerContractsIndexRoute
  DashboardHirerPaymentsIndexRoute: typeof DashboardHirerPaymentsIndexRoute
}

const DashboardHirerRouteRouteChildren: DashboardHirerRouteRouteChildren = {
  DashboardHirerMessagesRoute: DashboardHirerMessagesRoute,
  DashboardHirerProfileRoute: DashboardHirerProfileRoute,
  DashboardHirerIndexRoute: DashboardHirerIndexRoute,
  DashboardHirerContractsContractIdRoute:
    DashboardHirerContractsContractIdRoute,
  DashboardHirerJobsJobIdRoute: DashboardHirerJobsJobIdRouteWithChildren,
  DashboardHirerJobsNewRoute: DashboardHirerJobsNewRoute,
  DashboardHirerContractsIndexRoute: DashboardHirerContractsIndexRoute,
  DashboardHirerPaymentsIndexRoute: DashboardHirerPaymentsIndexRoute,
}

const DashboardHirerRouteRouteWithChildren =
  DashboardHirerRouteRoute._addFileChildren(DashboardHirerRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardFreelancerRouteRoute: typeof DashboardFreelancerRouteRouteWithChildren
  DashboardHirerRouteRoute: typeof DashboardHirerRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminVerificationsIndexRoute: typeof DashboardAdminVerificationsIndexRoute
  DashboardOnboardingRoleIndexRoute: typeof DashboardOnboardingRoleIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardFreelancerRouteRoute: DashboardFreelancerRouteRouteWithChildren,
  DashboardHirerRouteRoute: DashboardHirerRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminVerificationsIndexRoute: DashboardAdminVerificationsIndexRoute,
  DashboardOnboardingRoleIndexRoute: DashboardOnboardingRoleIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ForgotPasswordRouteRouteChildren {
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
}

const ForgotPasswordRouteRouteChildren: ForgotPasswordRouteRouteChildren = {
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
}

const ForgotPasswordRouteRouteWithChildren =
  ForgotPasswordRouteRoute._addFileChildren(ForgotPasswordRouteRouteChildren)

interface FreelancersRouteRouteChildren {
  FreelancersUserIdRoute: typeof FreelancersUserIdRoute
  FreelancersIndexRoute: typeof FreelancersIndexRoute
}

const FreelancersRouteRouteChildren: FreelancersRouteRouteChildren = {
  FreelancersUserIdRoute: FreelancersUserIdRoute,
  FreelancersIndexRoute: FreelancersIndexRoute,
}

const FreelancersRouteRouteWithChildren =
  FreelancersRouteRoute._addFileChildren(FreelancersRouteRouteChildren)

interface LoginRouteRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface ResetPasswordRouteRouteChildren {
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
}

const ResetPasswordRouteRouteChildren: ResetPasswordRouteRouteChildren = {
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
}

const ResetPasswordRouteRouteWithChildren =
  ResetPasswordRouteRoute._addFileChildren(ResetPasswordRouteRouteChildren)

interface SuccessRouteRouteChildren {
  SuccessIndexRoute: typeof SuccessIndexRoute
}

const SuccessRouteRouteChildren: SuccessRouteRouteChildren = {
  SuccessIndexRoute: SuccessIndexRoute,
}

const SuccessRouteRouteWithChildren = SuccessRouteRoute._addFileChildren(
  SuccessRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRouteRoute: ClientsRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ForgotPasswordRouteRoute: ForgotPasswordRouteRouteWithChildren,
  FreelancersRouteRoute: FreelancersRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  ResetPasswordRouteRoute: ResetPasswordRouteRouteWithChildren,
  SuccessRouteRoute: SuccessRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
