import { JOB_CATEGORY_SUGGESTIONS } from "@/lib/hirer-options";
import { SKILL_SUGGESTIONS } from "@/lib/profile-options";

const ADDITIONAL_JOB_SKILLS = [
  "HTML",
  "CSS",
  "SASS",
  "SCSS",
  "Bootstrap",
  "Material UI",
  "Redux",
  "Zustand",
  "TanStack Query",
  "React Query",
  "Webpack",
  "Vite",
  "Bun",
  "Express.js",
  "NestJS",
  "Elysia",
  "Hono",
  "Fastify",
  "Prisma",
  "Drizzle ORM",
  "Supabase",
  "Firebase",
  "MySQL",
  "SQLite",
  "Redis",
  "Elasticsearch",
  "Terraform",
  "Ansible",
  "CI/CD",
  "GitHub Actions",
  "Google Cloud",
  "Azure",
  "Microservices",
  "System Design",
  "API Design",
  "Swift",
  "Kotlin",
  "Objective-C",
  "iOS Development",
  "Android Development",
  "Unity",
  "Unreal Engine",
  "Game Development",
  "Blender",
  "After Effects",
  "Premiere Pro",
  "Photoshop",
  "Illustrator",
  "InDesign",
  "Canva",
  "Brand Identity",
  "Logo Design",
  "Wireframing",
  "Prototyping",
  "User Research",
  "Usability Testing",
  "Design Systems",
  "Copywriting",
  "Technical Writing",
  "Blog Writing",
  "Proofreading",
  "Editing",
  "Translation",
  "Social Media Marketing",
  "Email Marketing",
  "PPC",
  "Google Ads",
  "Facebook Ads",
  "Analytics",
  "Google Analytics",
  "HubSpot",
  "Salesforce",
  "CRM",
  "Lead Generation",
  "Market Research",
  "TensorFlow",
  "PyTorch",
  "NLP",
  "Computer Vision",
  "Deep Learning",
  "Data Engineering",
  "ETL",
  "Power BI",
  "Tableau",
  "Excel",
  "SQL",
  "R",
  "Statistics",
  "A/B Testing",
  "Cybersecurity",
  "Penetration Testing",
  "Network Security",
  "Blockchain",
  "Solidity",
  "Web3",
  "Smart Contracts",
  "Shopify",
  "WordPress",
  "WooCommerce",
  "Magento",
  "E-commerce",
  "QA Testing",
  "Selenium",
  "Cypress",
  "Jest",
  "Playwright",
  "Agile",
  "Scrum",
  "Jira",
  "Notion",
  "Customer Support",
  "Technical Support",
  "Virtual Assistant",
  "Data Entry",
  "Bookkeeping",
  "QuickBooks",
  "Legal Writing",
  "Contract Law",
  "CAD",
  "AutoCAD",
  "SolidWorks",
  "3D Modeling",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Product Design",
  "Product Strategy",
  "Business Analysis",
  "Financial Modeling",
  "Presentation Design",
  "Pitch Decks",
  "Voice Over",
  "Podcast Editing",
  "Sound Design",
  "Motion Graphics",
  "2D Animation",
  "3D Animation",
  "Character Design",
  "NFT Art",
  "Prompt Engineering",
  "ChatGPT",
  "LLM Integration",
  "OpenAI API",
  "Automation",
  "Zapier",
  "Make.com",
  "n8n",
] as const;

export const JOB_SKILL_SUGGESTIONS = [
  ...new Set([...SKILL_SUGGESTIONS, ...JOB_CATEGORY_SUGGESTIONS, ...ADDITIONAL_JOB_SKILLS]),
].sort((a, b) => a.localeCompare(b));
